In [3]:
import torch

In [27]:
lists=[]
lists.append(torch.tensor([1,2,3,4]))
lists.append(torch.tensor([5,6,7,8]))
print(torch.stack(lists))

z1=torch.randn(size=(1,3,4))
z2=torch.randn(size=(1,3,4))
torch.stack([z1,z2]).shape

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


torch.Size([2, 1, 3, 4])

In [16]:
import torch
query = torch.randn(256, 24, 11, 32)
key = torch.randn(256, 24, 11, 32)
print (query[255,23,10,:])
print (key.permute(0,1,3,2)[255,23,:,10])
print( torch.matmul(query[255,23,10,:],key.permute(0,1,3,2)[255,23,:,10]))
# Compute query * key^T using einsum
attention_scores = torch.einsum('b h s d, b h t d -> b h s t', query, key)  # Shape: [256, 24, 11, 11]
print(attention_scores.shape)
attention_scores[255,23,10,:]

tensor([-0.4757, -0.1663,  2.5720,  0.1699, -1.6417,  0.6582,  0.0340, -0.8705,
        -0.7395, -2.5497, -1.2543, -0.1447, -0.6209, -0.4240,  0.6552,  0.3811,
         0.4612,  0.6599, -0.8932,  1.0159,  1.4474, -0.3423, -0.8468, -0.1671,
        -0.2283,  0.5004, -0.6015,  0.8728,  0.5652,  0.3112,  0.6063,  1.4301])
tensor([-0.4623, -1.4982,  1.1602, -0.0520, -0.1778, -0.2938, -0.8891,  0.1880,
         0.6531,  0.7411,  0.3298,  1.7191,  0.1327, -0.9011,  0.3502,  0.2130,
        -0.3937, -0.3969,  0.1014,  1.1753,  0.4134, -1.5724, -0.5778,  0.8914,
        -0.9900, -0.8224, -0.2339, -0.9590,  0.4342,  1.7430, -0.9579, -1.1130])
tensor(0.7945)
torch.Size([256, 24, 11, 11])


tensor([  4.8226,  -3.4110,  16.8436,  -1.0903,   3.2480, -13.0524,   2.4728,
         -8.3740,  -7.1076, -10.8123,   0.7945])

In [10]:
import torch
query = torch.randn(256, 24, 11, 32)
query[0,0,0,0]=4.5
key = torch.randn(256, 24, 11, 32)
key[0,0,0,0]=4.5
torch.where(query==key)[0]

tensor([0])